/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.*;
import javax.swing.border.Border;


public class NewExamineeClass extends JFrame implements ActionListener {
       JLabel label, label1,label2, label3, bg;
    JTextField tfield, tfield1, tfield3;
    JTextField tfield2;
	JButton buttonSignup,buttonToken, btnback, btnlogin;

  

        
public NewExamineeClass(){
    
    Container c = getContentPane();
    
  setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(950,800);
        setTitle("Examinee Signup Form");
        
       setLayout(null);
       setLocationRelativeTo(null);

       btnlogin=new JButton("<html><u>Login</u></html>");
       btnlogin.setFont(new Font("Arial",Font.BOLD,20));
       btnlogin.setBounds(350, 510, 150, 30);    
       Border emptyBorder = BorderFactory.createEmptyBorder();
       btnlogin.setBorder(emptyBorder);
       btnlogin.setContentAreaFilled(false);
       btnlogin.setForeground(Color.WHITE);
       c.add(btnlogin); 
       btnlogin.addActionListener(this);
       
       buttonSignup=new JButton("Signup");
       buttonSignup.setBounds(250, 450, 160, 40);
       add(buttonSignup);
       buttonSignup.addActionListener(this);
        buttonSignup.setForeground(Color.WHITE);
        buttonSignup.setFont(new Font("Calibri",Font.BOLD,21));
      buttonSignup.setBackground(Color.BLACK);
      
      
        buttonToken=new JButton("Create Token");
       buttonToken.setBounds(430, 450, 188, 40);
       add(buttonToken);
       buttonToken.addActionListener(this);
        buttonToken.setForeground(Color.WHITE);
        buttonToken.setFont(new Font("Calibri",Font.BOLD,21));
      buttonToken.setBackground(Color.BLACK);
      
          btnback=new JButton("Back");
       btnback.setBounds(0, 0, 150, 30);
       add(btnback);
       btnback.addActionListener(this);
        btnback.setForeground(Color.WHITE);
        btnback.setFont(new Font("Calibri",Font.PLAIN,21));
      btnback.setBackground(Color.BLACK);
       
       tfield1=new JTextField();
       tfield1.setBounds(450,240,180,35);
       add(tfield1);
       
       tfield3=new JTextField();
        tfield3.setBounds(450,290,180,35);
        
       add(tfield3);
       
        tfield2=new JTextField();
        tfield2.setBounds(450,340,180,35);
        tfield2.setEditable(false);
       add(tfield2);
	
	label1=new JLabel("Student Username");
       label1.setBounds(250,240,250,40);
       add(label1);
       label1.setFont(new Font("Arial",Font.BOLD,19));
       label1.setForeground(Color.darkGray);
       
       label2=new JLabel("Student Email");
       label2.setBounds(250,290,250,40);
       add(label2);
       label2.setFont(new Font("Arial",Font.BOLD,19));
       label2.setForeground(Color.darkGray);
       
        label3=new JLabel("Password"); //generated by token
       label3.setBounds(250,340,250,40);
       add(label3);
       label3.setFont(new Font("Arial",Font.BOLD,19));
       label3.setForeground(Color.darkGray);
       setVisible(true);
          
            ImageIcon img = new ImageIcon("images/bg.jfif");
        bg=new JLabel("",img,JLabel.CENTER);
        bg.setBounds(0,0,950,800);
        add(bg);
      setResizable(false);
       
}
 public String tokenCreate() {
            int n = 10;
            String token = "abcdefghijklmnopqrstuvxyz"+ "ABCDEFGHIJKLMNOPQRSTUVWXYZ"+ "0123456789";  
            StringBuilder s = new StringBuilder(n); 
            for (int i = 0; i < n; i++) { 
            int index = (int)(token.length() * Math.random()); 
            s.append(token.charAt(index));
            }
            return s.toString();
    }   
  @Override
    public void actionPerformed(ActionEvent ae) {
          if(ae.getSource().equals(btnlogin)){
        new ExamineeLogin();
    }
        if(ae.getSource()==buttonSignup)
            
            
        {
              
            if (tfield1.getText().trim().equals("") || tfield2.getText().trim().equals("") || tfield3.getText().trim().equals("") ){       
           JOptionPane.showMessageDialog(null,"Field is left blank!");
            }
           else if(!tfield3.getText().contains("@")){
                      JOptionPane.showMessageDialog(null,"Invalid email!");
                   }
    
         
            else{
            
            try {
                database data=new database();
                int ans=data.insert(tfield1.getText(),tfield3.getText(),tfield2.getText()); //calling function 'insert'

                
                if(ans>0)
                {
                    JOptionPane.showMessageDialog(null,"Data has been saved");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Data cannot be saved");
                }
            } catch (Exception e) {
            }
             new ExamineeLogin();
            }
           
        }
        
           if (ae.getSource().equals(buttonToken)){
           
           tfield2.setText(tokenCreate());
             JOptionPane.showMessageDialog(null,"Please note the password for login!");
           
               }
              if (ae.getSource().equals(btnback)){
           
                new Application();
                this.dispose();
               }

}
}